# options: packer_build, dcos_installation, integration_tests, never. Default is dcos_installation. For more details, see README
# Muted tests:
# test_executor_metrics_metadata: https://jira.d2iq.com/browse/D2IQ-56252
publish_dcos_images_after: integration_tests
run_framework_tests: false
run_integration_tests: true
tests_to_run:
  - -k 'test_ipv6 and test_vip_ipv6 and test_vip and test_ip_per_container and test_app_networking_mode_with_defined_container_port and test_app_networking_mode_with_defined_container_port and test_service_discovery_docker_overlay'
