# options: packer_build, dcos_installation, integration_tests, never. Default is dcos_installation. For more details, see README
# You can also run custom tests with tests_to_run.
publish_dcos_images_after: never
run_framework_tests: false
run_integration_tests: false
# Muting known failing test, see https://jira.mesosphere.com/browse/DCOS-62478
#tests_to_run:
#  - -k 'test_networking'
